#!/bin/bash

TITLE="ontoread - a tool to read ontology"
USAGE="ontoread [filename [lang]] -- onto read the file"

if [ "$1" == "-h" ] || [ "$1" == "" ]
  then echo -e $TITLE
       echo -e "usage: " $USAGE 
   exit ; fi

FNAME=$1
LANG=$2

if [ "$LANG" == "" ] ; then LANG=RDF/XML ; fi

$HOME/work/ontoreader/ontoread.sh $FNAME $LANG
